version: "3"
tasks:
  gen grpc:
    desc: "generating Go files from proto"
    cmd:
      protoc -I api/proto api/proto/auth.proto --go_out=./gen/grpc/auth --go_opt=paths=source_relative --go-grpc_out=./gen/grpc/auth --go-grpc_opt=paths=source_relative

  gen api:
    desc: "generating go files from swagger/openapi file"
    cmd: echo "some test"